name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: npm build
      run: |
        npm install
        npm run all

    - name: upload-artifact
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: dist

  test: # make sure the action works on a clean machine without building
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: download-artifact from build
      uses: actions/download-artifact@v1
      with:
        name: my-artifact
        path: dist

    - uses: ./
      with: 
        folder: files
        outputFile: 'files/file-query-output.txt'
    - name: upload-artifact
      uses: actions/upload-artifact@v1
      with:
        name: found-files
        path: files

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}